### ISSUE TITLE
[feat] Support Terraform >= 1.4.0

### ISSUE THREAD

**Issue by ponkio-o** [suzuki-shunsuke/tfcmt#685] opened 2023-03-10 01:10 UTC
Hi @suzuki-shunsuke

Thanks for developing amazing tool!
[Terraform 1.4.0](https://github.com/hashicorp/terraform/releases/tag/v1.4.0) has been released and some messages seem to have changed.

As shown below, it should be "No changes" but an error occurs.
![image](https://user-images.githubusercontent.com/29038315/224197403-dff39d1a-c00f-46e3-a93e-ae9530b40d60.png)

Terraform 1.3.8
![image](https://user-images.githubusercontent.com/29038315/224198528-1644b8dd-7c5f-4873-aa87-c2e34ca38267.png)

Terraform 1.4.0
![image](https://user-images.githubusercontent.com/29038315/224198587-c7533785-c9b8-4138-8d1c-fc62d7a8286a.png)

Incidentally, when there were resource changes, they were correctly parsed.

**Comment by suzuki-shunsuke** [comment] 2023-03-10 01:15
Thank you for your report!
I'll take a look.

**Comment by suzuki-shunsuke** [comment] 2023-03-10 01:26
I couldn't reproduce the issue with simple configuration files.

```console
$ terraform version
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/null v3.2.1

$ tfcmt -v     
tfcmt version 4.2.0 (ca834049d0655ab9eec79e913aa7eacc362c2f9e)
```

main.tf

```tf
resource "null_resource" "foo" {}
```

```console
$ tfcmt plan -- terraform plan  
null_resource.foo: Refreshing state... [id=8530719906037906442]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

$ echo $?
0
```

A comment was posted successfully.

<img width="965" alt="image" src="https://user-images.githubusercontent.com/13323303/224199515-ec3b638d-916b-4387-9025-411d3230b75b.png">

**Comment by suzuki-shunsuke** [comment] 2023-03-10 01:28
Could you create a minimum code to reproduce the issue?
ref. https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce

**Comment by ponkio-o** [comment] 2023-03-10 01:46
I ran the same code and it correctly displayed "No changes". However, it is not displayed in the code used in production. 🤔 
I will do some more research to see under what conditions this error.

**Comment by ponkio-o** [comment] 2023-03-10 03:10
Sorry, This problem was not caused by tfcmt.

There seems to be a problem on the Terraform side, where "No changes." is not displayed when `outputs` is included.
https://github.com/hashicorp/terraform/issues/32815

The following code reproduces.

```hcl
resource "null_resource" "test" {}

output "test" {
  value = "some-text"
}
```

**Comment by suzuki-shunsuke** [comment] 2023-03-10 03:21
Thank you for your update.
Maybe is this related?
- https://github.com/suzuki-shunsuke/tfcmt/issues/117

**Comment by suzuki-shunsuke** [comment] 2023-03-10 03:23
Oh, sorry. I missed https://github.com/hashicorp/terraform/issues/32815

**Comment by ponkio-o** [comment] 2023-03-10 03:28
It seems related, but there are a few differences.

https://github.com/suzuki-shunsuke/tfcmt/issues/117 is when the difference in the `terraform plan` is a change in output only. (not "No changes")
https://github.com/suzuki-shunsuke/tfcmt/issues/685 (This Issue) is triggered if it contains output and the result is "No Changes".

**Comment by ponkio-o** [comment] 2023-03-16 01:04
Hi everyone,

Terraform v1.4.1 has been released. This release fixes this issue.
https://github.com/hashicorp/terraform/releases/tag/v1.4.1

**Comment by suzuki-shunsuke** [comment] 2023-03-16 01:09
Thank you for sharing!
Let's close this issue.

**Closed by suzuki-shunsuke** 2023-03-16 01:09 UTC
