### ISSUE TITLE
Message:Body is too long and tfcmt could not post comment to PR

### ISSUE THREAD

**Issue by guitarrapc** [suzuki-shunsuke/tfcmt#227] opened 2022-03-25 11:21 UTC
## Description of issue

When large change PR was create, tfcmt unable to POST changes to PR comment with following error.

> POST https://api.github.com/repos/OWNER/REPO/issues/NNN/comments: 422 Validation Failed [{Resource:IssueComment Field:data Code:unprocessable Message:Body is too long (maximum is 65536 characters)}]

## Summary

GitHub PR has limitation of PR comment length for 65536 characters, therefore some times tfcmt fail to post result.

Since tfcmt 3.0.0 and above compress `plan` result it rarely happens. But `apply` result still contains whole changes and often reached this limit.

## Expected behaviour

post changes to PR without error.

## Actual behaviour

tfcmt failed to post message. PR shows nothing and user need check GitHub Actions logs.

## Other idea

Pulumi also has similar behaviour of Posting changes to GitHub PR comments with `comment-on-pr: true`

> see; https://github.com/pulumi/actions

If message length is over 65536, then it split comment to another comment from terminated line.

**Comment by suzuki-shunsuke** [comment] 2022-03-25 11:35
Thank you for your report!

> If message length is over 65536, then it split comment to another comment from terminated line.

Oh, it's interesting.

github-comment supports posting substitute comment when it failed to post a too long comment.

https://github.com/suzuki-shunsuke/github-comment#post-a-substitute-comment-when-it-failed-to-post-a-too-long-comment

**Comment by suzuki-shunsuke** [comment] 2022-03-28 00:22
# Proposal: Add `short_templates` fields

Add `short_templates` fields, which is a list of templates.
If `template` is too long, `short_templates` are used.

e.g.

```yaml
terraform:
  plan:
    template:
    short_templates:
    - |
      {{template "plan_title" .}}

      {{if .Link}}[CI link]({{.Link}}){{end}}

      {{template "deletion_warning" .}}
      {{template "result" .}}
      {{template "updated_resources" .}}

      {{template "changed_result" .}}
      {{template "warning" .}}
      {{template "error_messages" .}}
    - |
      {{template "plan_title" .}}

      {{if .Link}}[CI link]({{.Link}}){{end}}

      {{template "deletion_warning" .}}
      {{template "result" .}}
      {{template "updated_resources" .}}

      {{template "warning" .}}
      {{template "error_messages" .}}
    - |
      {{template "plan_title" .}}

      {{if .Link}}[CI link]({{.Link}}){{end}}

      {{template "deletion_warning" .}}
      {{template "result" .}}
    when_parse_error:
      template:
      short_templates:
      - "..."
  apply:
    template:
    when_parse_error:
      template:
      short_templates:
      - "..."
    short_templates:
    - |
      {{template "plan_title" .}}

      {{if .Link}}[CI link]({{.Link}}){{end}}

      {{template "deletion_warning" .}}
      {{template "result" .}}
      {{template "updated_resources" .}}

      {{template "changed_result" .}}
      {{template "warning" .}}
      {{template "error_messages" .}}
    - |
      {{template "plan_title" .}}

      {{if .Link}}[CI link]({{.Link}}){{end}}

      {{template "deletion_warning" .}}
      {{template "result" .}}
      {{template "updated_resources" .}}

      {{template "warning" .}}
      {{template "error_messages" .}}
    - |
      {{template "plan_title" .}}

      {{if .Link}}[CI link]({{.Link}}){{end}}

      {{template "deletion_warning" .}}
      {{template "result" .}}
```

**Comment by suzuki-shunsuke** [comment] 2022-03-28 03:03
# Proposal 2: Omit long variables automatically

For example, if the variable `CombinedOutput` is too long, it is omitted as the following automatically.

```
aws_elb.foo_a: Modifying... [id=foo-a-production]
aws_elb.foo_a: Modifications complete after 2s [id=foo-a-production]

... # The content is omitted

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by suzuki-shunsuke** [comment] 2022-03-28 04:56
https://github.com/suzuki-shunsuke/tfcmt/pull/231

**Comment by suzuki-shunsuke** [comment] 2022-03-28 05:58
https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v3.1.0-0

**Comment by suzuki-shunsuke** [comment] 2022-03-31 01:52
I've released [v3.1.0](https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v3.1.0).
I expect this issue has been solved in almost cases by using the template function `wrapCode` properly.

**Comment by suzuki-shunsuke** [comment] 2022-03-31 09:33
I close this issue, but if you have any question or opinion, please comment.

**Closed by suzuki-shunsuke** 2022-03-31 09:33 UTC
Labels: enhancement

**Comment by guitarrapc** [comment] 2022-04-14 02:34
Sorry for late response. I've updated and seems working correct.
Thank you for prompt update!

**Comment by petr-stupka** [comment] 2024-01-10 19:18
Hi, there seems to be issue

![image](https://github.com/suzuki-shunsuke/tfcmt/assets/18548253/aba7bc26-fa2b-4ec7-b3b0-ecc0795c4443)

After the substitute, it still post the rest of the plan (unformatted). Pretty lengthy and doesn't seems to hit the limit

**Comment by suzuki-shunsuke** [comment] 2024-01-10 23:42
@petr-stupka
Please create a new discussion as this issue was old and already closed.
When you create a discussion, please add a link to this issue.

https://github.com/suzuki-shunsuke/tfcmt/discussions/new?category=support-request

Short answer: I think this is not an issue but an expected behaviour.
