### ISSUE TITLE
Fail to update label color, surfaced as ⚠️ Errors

### ISSUE THREAD

**Issue by Cheezmeister** [suzuki-shunsuke/tfcmt#469] opened 2022-10-03 20:59 UTC
At https://github.com/teikametrics, we are gradually introducing `tfcmt` into our workflow.

One problem we have is encountering the below error, which does not prevent the comment from being posted, but does itself show up in the comment that's produced. The label is still created if it doesn't exist, just fine.

```
ERRO[0001] update a label color                          color=d93f0b error="PATCH https://api.github.com/repos/teikametrics/tm-infra-shared/labels/destroy: 404 Not Found []" label=destroy program=tfcmt
```

<img width="794" alt="image" src="https://user-images.githubusercontent.com/576853/193677937-9e4f2374-4af5-44cf-9d8f-da77dcab30b7.png">

Most of our devs are not fluent in Terraform, and simply following instrutions. I worry that they'll see this and think that there is a problem with their code. In fact the only problem is we have simply a sad, colorless label 😅 

It's a private repository, and the `GITHUB_TOKEN` we use is that of a shared user with only these scopes as shown:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/576853/193679394-9348307b-d78f-47c9-87d9-14ae16d25943.png">

As the [documentation](https://suzuki-shunsuke.github.io/tfcmt/getting-started#setup) doesn't speak to which scopes are required, I made my best guess. The doc for the `PATCH` endpoint doesn't mention it either. https://docs.github.com/en/rest/issues/labels#update-a-label

Any advice is appreciated.

**Comment by suzuki-shunsuke** [comment] 2022-10-03 21:52
I couldn't reproduce this issue with tfcmt v4.0.0.
I could create a label and update a label color.

I think tfcmt requires only `repo` permission, so your setting has no problem.

Could you tell me how to reproduce?

- `tfcmt -v`
- configuration file `tfcmt.yaml`
- command and output

ref. https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce

**Comment by Cheezmeister** [comment] 2022-10-17 20:09
Thanks, @suzuki-shunsuke , for the speedy response and clear instructions 👍 

I'm working on putting together a minimal repro. It will take some time, as I'm pretty sure a private repo is needed, and want to make your life easy. I'll report back when it's ready.

For now, I can tell you that we're on v4.0.0-3:

```console
$ tfcmt -v
tfcmt version 4.0.0-3 (04346bd5cec9b1919cbcc84b7b57413321395273)
```

We don't use a `tfcmt.yaml` currently. We're working with the tool's out-of-the-box defaults (https://suzuki-shunsuke.github.io/tfcmt/config#default-configuration).

**Comment by suzuki-shunsuke** [comment] 2022-10-17 23:37
v4.0.0-3 is a prerelease version, so could you use the latest stable version [v4.0.0](https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v4.0.0)?

**Comment by Cheezmeister** [comment] 2022-12-16 20:57
Using v4.0.0 gives us the same results. However, once I changed the user's role from "Triage" to "Write" (under `/settings/access`, **Collaborators and teams**), then the problem went away. <small>[1]</small>

So I think, it might be a not a token problem, but instead a user/repo problem.

Unfortunately, I can't add you to the private repo that I used to reproduce, without spending more money 💸 So, feel free to close this issue, or investigate further on your own. I may go [raise an issue](https://github.com/github/docs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) against the rest API docs, and if my guess is correct maybe @github will document this edge case 🙂 

<small>[1]</small>
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/576853/208184999-202f50da-a5ed-476c-9e0b-52f55691d131.png">

**Comment by suzuki-shunsuke** [comment] 2023-01-07 07:52
Sorry for late reply. And thank you for your update.
Labels belong to not issues and pull requests but repositories, so I guess `Triage` doesn't have enough permission to update label colors.
I close this issue.

**Closed by suzuki-shunsuke** 2023-01-07 07:52 UTC
