### ISSUE TITLE
Even if only 'moved' is used, tfcmt reports it as an 'add-or-update' label.

### ISSUE THREAD

**Issue by guitarrapc** [suzuki-shunsuke/tfcmt#1312] opened 2024-06-14 01:54 UTC
### Feature Overview

If there are no changes on resources, tfcmt should report it as an`no-changes` label.

### Why is the feature needed?

When no `moved` block is used and no changes happen, tfcmt report `no-changes` label. However if I use `moved` block and result was no changes, tfcmt reports it as an `add-or-update` label. I would expect tfcmt to report `no-changes`, because `moved` block is just a refactoring code and no resource changes are happen.

Following to official doc, tfcmt's label is tareget to resource change identification, NOT state change... I believe.

```
no-changes: there is no resource to be changed
add-or-update: there are resources to be created or updated but there is no resource to be destroyed or recreated
destroy: there are resources to be destroyed or recreated
```

### Example Code

```console
$ tfcmt plan -patch -- terraform plan -no-color
```

Configuration

```yaml
moved {
  from = old_module.reousrce.main
  to   = new_module.resource.main
}
```

### note

If tfcmt is looking state change, then current behaiviour is correct.

**Comment by suzuki-shunsuke** [comment] 2024-07-11 21:17
Duplicate of #358

**Comment by guitarrapc** [comment] 2024-07-12 04:01
Should I close?

**Comment by suzuki-shunsuke** [comment] 2024-07-12 04:25
Let me close.

**Closed by suzuki-shunsuke** 2024-07-12 04:25 UTC
Labels: enhancement
